### PR TITLE
Update client_side2.py

### PR DESCRIPTION
**Pull request by Jsavaia**
updated client side with all errors handling

### CODE REVIEW

**Comment by Jsavaia** [comment]
double check pls

**Comment by jsantos984** [comment]
This change created a conflict. We need to fix it before merge

**Comment by Jsavaia** [comment]
yes of course I had to change the code there to make it work...like this is handling exceptions way better than before, and it was working fine.....we can leave it as it was before if you prefer...

**Comment by jsantos984** [comment]
Does this change blocks any tests? Or all the tests are still performing well?

**Comment by Jsavaia** [comment]
No the test are working perfectly fine with that change. Because first I changed the code on the client and after I implemented the tests on that code changed.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
